version: '3.4'

services:
  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    ports:
      - "8010:80"
    depends_on:
      - basketdb
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"